### ISSUE TITLE
There's a case where the secret cannot not be restored by the shares

### ISSUE THREAD

**Issue by lubokkanev** [mohrt/secretcoin#2]
If the number of shares is lower than the threshold, the generated shares cannot be used to restore the secret. There should be a check if that's the case and an error should be thrown.

**Comment by lubokkanev** [comment]
Hey @GitCash, pay $1 to this fine gentleman: @mohrt

**Comment by GitCash** [comment]
Hey **mohrt**, user **lubokkanev** tipped you **4878 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/mohrt)*

You can also add the "thumbs down" reaction to **lubokkanev**'s comment above to prevent future tips.
